# Generated by Django 6.0.7 on 2026-08-15 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('background', models.CharField(default='black')),
                ('like', models.BooleanField(default=False)),
                ('comment', models.BooleanField(default=False)),
                ('share', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ImageFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='img/')),
                ('title', models.CharField(max_length=500)),
                ('like', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=20)),
                ('likecount', models.IntegerField(default=0)),
                ('comment', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=20)),
                ('commentcount', models.IntegerField(default=0)),
                ('share', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=20)),
                ('sharecount', models.IntegerField(default=0)),
                ('original_feed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_posts', to='feeds.imagefeed')),
            ],
        ),
    ]
