# Generated by Django 6.0.7 on 2026-09-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textfeed',
            name='background',
            field=models.CharField(max_length=100),
        ),
    ]
